[package]
name = "volition-agent-core"
version = "0.1.0"
edition = "2021"
authors = ["Jesse B. Miller <jesse@jessebmiller.com>"]
description = "Core library for the Volition AI agent"

[lib]
name = "volition_agent_core"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }
toml = { workspace = true }
ignore = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
httpmock = { workspace = true }
tracing-subscriber = { workspace = true } # Added for agent tests
