name: Publish to crates.io

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Build and test
        run: |
          cargo build --release
          cargo test --release

      - name: Log in to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish with cargo-workspaces
        run: |
          cargo workspaces publish --from-git --skip-published --no-git-commit --token ${{ secrets.CRATES_IO_TOKEN }}
