name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'

jobs:
  release:
    environment: release
    uses: semantic-release-action/rust/.github/workflows/release-library.yml@v5
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
