name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install semantic-release-rust
        run: |
          cargo install semantic-release-rust
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec

      - name: Create .releaserc.json
        run: |
          cat > .releaserc.json << 'EOF'
          {
            "branches": [
              "main",
              "next",
              {
                "name": "beta",
                "prerelease": true
              },
              {
                "name": "alpha",
                "prerelease": true
              }
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              ["@semantic-release/changelog", {
                "changelogFile": "CHANGELOG.md"
              }],
              ["@semantic-release/exec", {
                "verifyConditionsCmd": "semantic-release-rust verify-conditions",
                "prepareCmd": "semantic-release-rust prepare ${nextRelease.version}",
                "publishCmd": "semantic-release-rust publish"
              }],
              ["@semantic-release/git", {
                "assets": ["Cargo.toml", "Cargo.lock", "CHANGELOG.md"],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }],
              "@semantic-release/github"
            ]
          }
          EOF

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: semantic-release
